{
 "title": "Web API dashboard",
 "description": "Flask Application Dashboard",
 "tags": [
  "flask",
  "web-api"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(flask_http_request_total{job=\"web-api\", method!=\"OPTIONS\", url_rule!=\"/api/metrics\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(flask_http_request_total{job=\"web-api\", method!=\"OPTIONS\", url_rule!=\"/api/metrics\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total requests per minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(flask_http_request_total{namespace=~'$namespace', pod=~'$pod'}[1m])",
     "legendFormat": "HTTP-{{method}} {{ status }}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{namespace=~'$namespace', pod=~'$pod', status!=\"200\"}[1m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "process open fds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(process_open_fds{job=\"web-api\", namespace=~'$namespace', pod=~'$pod'})",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{namespace=~'$namespace', pod=~'$pod', status=\"200\"}[1m])",
     "legendFormat": "{{url_rule}}{{path}}"
    }
   ]
  },
  {
   "title": "Average response time [1m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{namespace=~'$namespace', pod=~'$pod', status=\"200\"}[1m])\n/\nrate(flask_http_request_duration_seconds_count{namespace=~'$namespace', pod=~'$pod', status=\"200\"}[1m])",
     "legendFormat": "{{url_rule}}{{path}}"
    }
   ]
  },
  {
   "title": "Requests under 250ms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "increase(flask_http_request_duration_seconds_bucket{namespace=~'$namespace', pod=~'$pod', status=\"200\",le=\"0.25\"}[1m]) \n/ ignoring (le) increase(flask_http_request_duration_seconds_count{namespace=~'$namespace', pod=~'$pod', status=\"200\"}[1m])",
     "legendFormat": "{{url_rule}}{{path}}"
    }
   ]
  },
  {
   "title": "Request duration [s] - 0.5",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(flask_http_request_duration_seconds_bucket{namespace=~'$namespace', pod=~'$pod', status=\"200\"}[1m]))",
     "legendFormat": "{{url_rule}}{{path}}"
    }
   ]
  },
  {
   "title": "Request duration [s] - 0.9",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(flask_http_request_duration_seconds_bucket{namespace=~'$namespace', pod=~'$pod', status=\"200\"}[1m]))",
     "legendFormat": "{{url_rule}}{{path}}"
    }
   ]
  }
 ]
}