apiVersion: v1
kind: ServiceAccount
metadata:
  name: shopnow-postgres-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: shopnow-postgres-exporter
    app.kubernetes.io/part-of: portfolio-monitoring
    app.kubernetes.io/component: exporter
    app.kubernetes.io/managed-by: argocd
