apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pushgateway-pvc
  namespace: monitoring
  labels:
    app.kubernetes.io/name: pushgateway
    app.kubernetes.io/part-of: portfolio-monitoring
    app.kubernetes.io/component: metrics
    app.kubernetes.io/managed-by: argocd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
