apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: portfolio-user-ui-pdb
  namespace: portfolio
  labels:
    app: portfolio-mcs
    component: user-ui
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: portfolio-mcs
      component: user-ui
